version: "3.9"

services:
  api-1:
    build:
      dockerfile: ./Dockerfile
    hostname: api-1
    container_name: rinha-api-1
    ports:
      - "3000:3000"
    networks:
      - rinha-network

  api-2:
    build:
      dockerfile: ./Dockerfile
    hostname: api-2
    container_name: rinha-api-2
    ports:
      - "8082:8080"
    networks:
      - rinha-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
    networks:
      - rinha-network


networks:
  rinha-network:
    driver: host
